name: Testing
on: [push]
jobs:
  e2e:
    name: 'Build + E2E tests'
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DATABASE: trpcdb
          POSTGRES_USER: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
    env:
      NODE_ENV: test
      NEXTAUTH_SECRET: supersecret
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 8.5.1

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install deps (with cache)
        run: bun install

      - name: Setup Prisma
        run: bun prebuild

      - run: bun build
      - run: bun test:e2e

      - name: Check types
        run: bun tsc

  unit:
    name: 'Unit tests + typecheck'
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DATABASE: trpcdb
          POSTGRES_USER: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
    env:
      NODE_ENV: test
      NEXTAUTH_SECRET: supersecret
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 8.5.1

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install deps (with cache)
        run: bun install
        
      - name: Setup Prisma
        run: bun prebuild

      - run: bun test:unit
      - run: bun tsc
